# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install postgresql
      if: runner.os == 'Linux'

    - name: Start PostgreSQL
      run: sudo service postgresql start
      if: runner.os == 'Linux'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Stop PostgreSQL
      run: sudo service postgresql stop
      if: runner.os == 'Linux'
